### ISSUE TITLE
Unable to test Nova

### ISSUE THREAD

**Issue by dkulyk** [laravel/nova-dusk-suite#21]
In different runs of tests I have different results:
![image](https://user-images.githubusercontent.com/370042/57053065-462fad00-6c94-11e9-9fa8-8edeb973d456.png)

Maybe should use waitFor or something else instead pauses?

**Comment by rodrigore** [comment]
Maybe you should try to update Laravel Dusk (composer update) and then update the chrome driver using:
`php artisan dusk:chrome-driver`

Nevertheless, I still have some test fail, but updating the driver helps me.
