### ISSUE TITLE
Laravel nova cannot handle tab selector

### ISSUE THREAD

**Issue by mwafi06** [laravel/nova-dusk-suite#24]
I have a problem like this:
I want to call the selector tab in the laravel dusk component, this is a screenshot of the image I mean https://imgur.com/EvSTND9
I have tried various things like copy selector, xpath selector, and many ways but still failed. following my source code
```
$browser->click('Izin Penilaian KJPP')
 ->pause(3000)
 ->clickLink('Tambahkan Izin Penilaian KJPP');
```

**Comment by davidhemphill** [comment]
This is not related to Nova's Dusk test suite. This is a question for the 3rd-party package your using. :-)
